<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TMapEditor</AssemblyName>
    <RootNamespace>TMapEditor</RootNamespace>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon.ico" />
    <PackageReference Include="Aprillz.MewUI" Version="0.19.1" />
    <PackageReference Include="Aprillz.MewUI.Skia" Version="0.19.1" />
    <PackageReference Include="Aprillz.MewUI.Skia.Interop.Direct2D" Version="0.19.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
  </ItemGroup>
</Project>
